# Generated by Django 3.2.4 on 2021-06-25 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sells', models.CharField(blank=True, default='R$ 00,00', max_length=255, null=True)),
                ('sells_numbers', models.CharField(blank=True, default='0', max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade solicitada desse produto')),
                ('finally_price', models.CharField(blank=True, default='R$ 00,00', max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.product')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesman.salesman')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ('product',),
            },
        ),
    ]
