# Generated by Django 3.2.4 on 2021-06-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_auto_20210626_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='sell',
            name='quantity',
            field=models.CharField(max_length=10, null=True, verbose_name='Quantidade'),
        ),
    ]
